name: Execute Colab Notebook

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # Exécute à 8h00 UTC tous les jours

jobs:
  execute-notebook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install papermill jupyter pandas numpy gspread oauth2client

    - name: Download Notebook
      run: |
        curl -L https://raw.githubusercontent.com/marieandrepayfit/Marie-Andr-/main/Automation_Daily_Occupancy.ipynb > Automation_Daily_Occupancy.ipynb

    - name: Execute Jupyter Notebook
      env:
        DRIVE_API_KEY: ${{ secrets.DRIVE_API_KEY }}
      run: |
        papermill Automation_Daily_Occupancy.ipynb OutputNotebook.ipynb -p API_KEY "${{ env.DRIVE_API_KEY }}"
